[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
nexgent_token_lock_program = "47YGQvDJJzMAAq7Z6x7LegYhS5Dremk5sGRYGjkAM7c2"

[programs.mainnet]
nexgent_token_lock_program = "47YGQvDJJzMAAq7Z6x7LegYhS5Dremk5sGRYGjkAM7c2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
